name: Build
on:
  push:
    branches:
      - $default-branch
    tags:
      - '*'
  pull_request:
    branches:
      - $default-branch
jobs:
  # build_code:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v3
  #       with:
  #         distribution: 'temurin'
  #         java-version: '17'
  #         cache: 'sbt'
  #     - name: Run tests
  #       run: sbt test
  build_doc:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Build and Deploy'
        run: bash ./build.sh
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: doc
          TOKEN: ${{ secrets.TOKEN }}
